apiVersion: v1
kind: ConfigMap
metadata:
  name: rer-config
  namespace: rer-uzh
data:
  DB_NAME: rer_db
  DB_HOST: 10.50.10.30
  DB_PORT: "5432"

  REDIS_URL: redis://10.50.10.40:6379/0

  ALLOWED_HOSTS: "rer.uzh.ch,api.rer.uzh.ch"
  CORS_ALLOWED_ORIGINS: "https://rer.uzh.ch"

  SITE_CODE: "UZH"
  SITE_NAME: "Universität Zürich"
  VPN_SUBNET: "10.51.0.0/24"
  LOCAL_LAN_SUBNET: "10.50.10.0/24"

  API_URL: "http://django-service:8000"


