apiVersion: v1
kind: ConfigMap
metadata:
  name: rer-config
  namespace: rer-oxf
data:
  DB_NAME: rer_db
  DB_HOST: 10.40.10.30
  DB_PORT: "5432"

  REDIS_URL: redis://10.40.10.40:6379/0

  ALLOWED_HOSTS: "rer.ox.ac.uk,api.rer.ox.ac.uk"
  CORS_ALLOWED_ORIGINS: "https://rer.ox.ac.uk"

  SITE_CODE: "OXF"
  SITE_NAME: "University of Oxford"
  VPN_SUBNET: "10.41.0.0/24"
  LOCAL_LAN_SUBNET: "10.40.10.0/24"

  API_URL: "http://django-service:8000"


