apiVersion: v1
kind: ConfigMap
metadata:
  name: rer-config
  namespace: rer-lmu
data:
  DB_NAME: rer_db
  DB_HOST: 10.60.10.30
  DB_PORT: "5432"

  REDIS_URL: redis://10.60.10.40:6379/0

  ALLOWED_HOSTS: "rer.lmu.de,api.rer.lmu.de"
  CORS_ALLOWED_ORIGINS: "https://rer.lmu.de"

  SITE_CODE: "LMU"
  SITE_NAME: "Ludwig-Maximilians-Universität München"
  VPN_SUBNET: "10.61.0.0/24"
  LOCAL_LAN_SUBNET: "10.60.10.0/24"

  API_URL: "http://django-service:8000"


