apiVersion: v1
kind: ConfigMap
metadata:
  name: rer-config
  namespace: rer-cam
data:
  DB_NAME: rer_db
  DB_HOST: 10.30.10.30
  DB_PORT: "5432"

  REDIS_URL: redis://10.30.10.40:6379/0

  ALLOWED_HOSTS: "rer.cam.ac.uk,api.rer.cam.ac.uk"
  CORS_ALLOWED_ORIGINS: "https://rer.cam.ac.uk"

  SITE_CODE: "CAM"
  SITE_NAME: "University of Cambridge"
  VPN_SUBNET: "10.31.0.0/24"
  LOCAL_LAN_SUBNET: "10.30.10.0/24"

  API_URL: "http://django-service:8000"


