apiVersion: v1
kind: ConfigMap
metadata:
  name: rer-config
  namespace: rer-uha
data:
  DB_NAME: rer_db
  DB_HOST: 10.20.10.30
  DB_PORT: "5432"

  REDIS_URL: redis://10.20.10.40:6379/0

  ALLOWED_HOSTS: "rer.uha.fr,api.rer.uha.fr"
  CORS_ALLOWED_ORIGINS: "https://rer.uha.fr"

  SITE_CODE: "UHA"
  SITE_NAME: "Universit√© de Haute-Alsace"
  VPN_SUBNET: "10.21.0.0/24"
  LOCAL_LAN_SUBNET: "10.20.10.0/24"

  API_URL: "http://django-service:8000"


